### ISSUE TITLE
FormComponent.js

### ISSUE THREAD

**Issue by Braflee** [Braflee/group-project#21]
-Assign inputs and corresponding elements to tie with state
-pass props
-create buttons for submit, refresh, delete, and edit
-decide how to implement those onClick functions

**Comment by jspiper** [comment]
202106626 - Completed form outline include top-text and bottom-text fields. Complete handleChange and handleSubmit functions.

**Comment by jspiper** [comment]
20210627 - Worked on returning the meme image on the form which is current not working. Continuing to work on the needed functions for the other buttons (Edit, Delete, Refresh).

**Comment by jspiper** [comment]
20210629 - Completed `handleDelete` and refactored to access `url` and `id`.  Added `UUIDv4` for generating unique IDs. This lest is adding multiple memes of the same image with different captions. `hanldeEdit` is pending completion.

**Comment by jspiper** [comment]
Feature complete. Fixed bugs on `handleEdit` and the ability to edit memes in user list.
